const sprueche = [
  "💭 Fehler sind die besten Lehrer – auch wenn sie nerven 🌈",
  "🐾 Code kann warten. Kaffee nicht 📱",
  "💪 Manchmal ist Plan B besser als Plan A 🌙",
  "🧠 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🗂️",
  "😄 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🛠️",
  "🍀 Manchmal ist Plan B besser als Plan A 🌟",
  "🎨 Nicht perfekt ist auch okay 🌀",
  "😊 Manchmal ist Plan B besser als Plan A 🌞",
  "✌️ Hast du heute schon dein Lieblings-Ich gesehen? ⏸️",
  "🎯 Wenn Sunny könnte, würde sie jetzt auch scrollen 🔄",
  "🐾 Lächeln ist die eleganteste Art, dem Tag zu begegnen 🤝",
  "😎 Der beste Plan? Spontan 🎈",
  "🛋️ Heute schon gedacht? Morgen wird besser! 🕰️",
  "🧸 Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst 🎁",
  "🎨 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🌀",
  "💪 Wer fragt, führt. Wer lacht, lebt. 🌙",
  "🐶 Lächeln ist die eleganteste Art, dem Tag zu begegnen 💛",
  "🧸 Sunny sagt: Lieber Pfote geben als aufgeben 🎁",
  "🧸 Code kann warten. Kaffee nicht 🎁",
  "🔒 Sunny findet dich klasse – und sie hat Geschmack 🗝️",
  "🧸 Wenn Sunny könnte, würde sie jetzt auch scrollen 🎁",
  "🐾 Lernen darf Spaß machen – und manchmal Unsinn 🤝",
  "😊 Der beste Plan? Spontan 🌞",
  "✌️ Der beste Plan? Spontan 🚀",
  "💡 Kreativität beginnt da, wo der Plan aufhört 🧩",
  "💭 Code kann warten. Kaffee nicht 🌈",
  "😎 Digitale Welt – echte Gefühle 🎈",
  "📅 Code kann warten. Kaffee nicht 🤔",
  "✍️ Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst 📄",
  "🧠 Hast du heute schon dein Lieblings-Ich gesehen? 🎉",
  "✌️ Weniger scrollen, mehr erleben. (nach dieser Seite 😁) 🚀",
  "🧠 Kreativität beginnt da, wo der Plan aufhört 🎉",
  "🎧 Fehler sind die besten Lehrer – auch wenn sie nerven 🔊",
  "🐶 Wer fragt, führt. Wer lacht, lebt. 💛",
  "🪞 Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst ⭐",
  "💻 Nicht perfekt ist auch okay ❤️",
  "😎 Nur weil du Pause machst, heißt das nicht, dass du aufgibst 🎈",
  "🎧 Lernen darf Spaß machen – und manchmal Unsinn 🔊",
  "🐾 Kreativität beginnt da, wo der Plan aufhört 📱",
  "☕ Lächeln ist die eleganteste Art, dem Tag zu begegnen 💤",
  "📵 Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst 🌳",
  "🐾 Einfach mal machen. Wird schon irgendwie 🤝",
  "🧸 Der beste Plan? Spontan 🎁",
  "🧠 Nur weil du Pause machst, heißt das nicht, dass du aufgibst 🗂️",
  "✍️ Hast du heute schon dein Lieblings-Ich gesehen? 📄",
  "🪞 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist ⭐",
  "🔒 Kreativität beginnt da, wo der Plan aufhört 🗝️",
  "✌️ Lernen darf Spaß machen – und manchmal Unsinn ⏸️",
  "🦸‍♂️ Code kann warten. Kaffee nicht ✨",
  "📵 Wer fragt, führt. Wer lacht, lebt. 🌳",
  "✍️ Code kann warten. Kaffee nicht 📄",
  "🎧 Wer fragt, führt. Wer lacht, lebt. 🔊",
  "😄 Lächeln ist die eleganteste Art, dem Tag zu begegnen 🛠️",
  "🎯 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🔄",
  "🦸‍♂️ Weniger scrollen, mehr erleben. (nach dieser Seite 😁) ✨",
  "🧸 Fehler sind die besten Lehrer – auch wenn sie nerven 🎁",
  "😎 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🎈",
  "🧸 Wer fragt, führt. Wer lacht, lebt. 🎁",
  "🐾 Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst 📱",
  "💭 Kreativität beginnt da, wo der Plan aufhört 🌈",
  "🙋‍♂️ Ein leeres Textfeld ist auch ein Anfang 😂",
  "🎯 Hast du heute schon dein Lieblings-Ich gesehen? 🔄",
  "☕ Lernen darf Spaß machen – und manchmal Unsinn 💤",
  "🧸 Hast du heute schon dein Lieblings-Ich gesehen? 🎁",
  "🍀 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🌟",
  "🛋️ Sunny findet dich klasse – und sie hat Geschmack 🕰️",
  "💭 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🌈",
  "🎨 Der beste Plan? Spontan 🌀",
  "🎨 Manchmal ist Plan B besser als Plan A 🌀",
  "💭 Wenn Sunny könnte, würde sie jetzt auch scrollen 🌈",
  "💭 Digitale Welt – echte Gefühle 🌈",
  "🍞 Der beste Plan? Spontan 🥖",
  "🪞 Nicht perfekt ist auch okay ⭐",
  "🧠 Gönn dir ’ne Pause – du bist nicht Google 🎉",
  "🧠 Lernen darf Spaß machen – und manchmal Unsinn 🎉",
  "📚 Lernen darf Spaß machen – und manchmal Unsinn 😅",
  "🔒 Mut heißt nicht laut sein. Manchmal ist es einfach nur 'trotzdem weiter' 🗝️",
  "🛋️ Hast du heute schon dein Lieblings-Ich gesehen? 🕰️",
  "💡 Digitale Welt – echte Gefühle 🧩",
  "🧘‍♂️ Ein leeres Textfeld ist auch ein Anfang 📶",
  "💪 Kreativität beginnt da, wo der Plan aufhört 🌙",
  "🍞 Mut heißt nicht laut sein. Manchmal ist es einfach nur 'trotzdem weiter' 🥖",
  "💡 Wer fragt, führt. Wer lacht, lebt. 🧩",
  "📅 Nicht perfekt ist auch okay 🤔",
  "😄 Nicht perfekt ist auch okay 🛠️",
  "🔒 Hast du heute schon dein Lieblings-Ich gesehen? 🗝️",
  "💪 Wenn Sunny könnte, würde sie jetzt auch scrollen 🌙",
  "🎧 Gedanken sortieren ist wie Schubladen aufräumen – dauert, lohnt sich 🔊",
  "✌️ Mut heißt nicht laut sein. Manchmal ist es einfach nur 'trotzdem weiter' ⏸️",
  "😎 Heute ein Held sein – reicht schon für dich selbst 🎈",
  "💪 Nur weil du Pause machst, heißt das nicht, dass du aufgibst 🌙",
  "💪 Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🌙",
  "🧠 Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst 🎉",
  "✌️ Sunny sagt: Lieber Pfote geben als aufgeben ⏸️",
  "🧠 Weniger scrollen, mehr erleben. (nach dieser Seite 😁) 🎉",
  "💪 Sunny findet dich klasse – und sie hat Geschmack 🌙",
  "🧠 Lächeln ist die eleganteste Art, dem Tag zu begegnen 🎉",
  "🐾 Heute schon gedacht? Morgen wird besser! 🤝",
  "😄 Gedanken sortieren ist wie Schubladen aufräumen – dauert, lohnt sich 🛠️",
  "🦸‍♂️ Wer fragt, führt. Wer lacht, lebt. ✨",
  "💭 Gönn dir ’ne Pause – du bist nicht Google 🌈",
  "📅 Gönn dir ’ne Pause – du bist nicht Google 🤔",
  "🐾 Lernen darf Spaß machen – und manchmal Unsinn 📱",
  "🪞 Wenn Sunny könnte, würde sie jetzt auch scrollen ⭐",
  "😊 Nur weil du Pause machst, heißt das nicht, dass du aufgibst 🌞",
  "📚 Gönn dir ’ne Pause – du bist nicht Google 😅",
  "🧠 Manchmal ist Plan B besser als Plan A 🗂️",
  "🐾 Weniger scrollen, mehr erleben. (nach dieser Seite 😁) 📱",
  "✌️ Einfach mal machen. Wird schon irgendwie ⏸️",
  "✌️ Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist 🚀",
  "💪 Hast du heute schon dein Lieblings-Ich gesehen? 🌙",
  "📵 Mut heißt nicht laut sein. Manchmal ist es einfach nur 'trotzdem weiter' 🌳",
  "✌️ Digitale Welt – echte Gefühle ⏸️",
  "🧸 Gönn dir ’ne Pause – du bist nicht Google 🎁",
  "🛋️ Manchmal ist Plan B besser als Plan A 🕰️",
  "🧠 Der beste Plan? Spontan 🎉",
  "🐶 Mut heißt nicht laut sein. Manchmal ist es einfach nur 'trotzdem weiter' 💛",
  "💡 Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst 🧩",
  "🦸‍♂️ Hast du heute schon dein Lieblings-Ich gesehen? ✨",
  "🍞 Gedanken sortieren ist wie Schubladen aufräumen – dauert, lohnt sich 🥖",
  "🐶 Ein leeres Textfeld ist auch ein Anfang 💛",
  "🎯 Digitale Welt – echte Gefühle 🔄",
  "🛋️ Einfach mal machen. Wird schon irgendwie 🕰️",
  "😄 Weniger scrollen, mehr erleben. (nach dieser Seite 😁) 🛠️",
  "😎 Fehler sind die besten Lehrer – auch wenn sie nerven 🎈",
  "🧠 Ein leeres Textfeld ist auch ein Anfang 🗂️",
  "✍️ Manchmal ist Plan B besser als Plan A 📄",
  "🧠 Lächeln ist die eleganteste Art, dem Tag zu begegnen 🗂️",
  "🍞 Heute schon gedacht? Morgen wird besser! 🥖",
  "🧠 Kreativität beginnt da, wo der Plan aufhört 🗂️",
  "🍞 Heute ein Held sein – reicht schon für dich selbst 🥖",
  "😊 Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst 🌞",
  "📚 Wenn Sunny könnte, würde sie jetzt auch scrollen 😅",
  "🎨 Lernen darf Spaß machen – und manchmal Unsinn 🌀",
  "🎯 Lächeln ist die eleganteste Art, dem Tag zu begegnen 🔄",
  "✌️ Nur weil es nicht im Kalender steht, heißt das nicht, dass es unwichtig ist ⏸️",
  "📵 Lernen darf Spaß machen – und manchmal Unsinn 🌳",
  "🍀 Gedanken sortieren ist wie Schubladen aufräumen – dauert, lohnt sich 🌟",
  "🔒 Ein leeres Textfeld ist auch ein Anfang 🗝️",
  "😄 Heute ein Held sein – reicht schon für dich selbst 🛠️",
  "😄 Heute schon gedacht? Morgen wird besser! 🛠️",
  "💭 Nur weil du Pause machst, heißt das nicht, dass du aufgibst 🌈",
  "📚 Heute schon gedacht? Morgen wird besser! 😅",
  "🍞 Code kann warten. Kaffee nicht 🥖",
  "🎯 Heute schon gedacht? Morgen wird besser! 🔄",
  "📚 Manchmal ist Plan B besser als Plan A 😅",
  "🐾 Gedanken sortieren ist wie Schubladen aufräumen – dauert, lohnt sich 🤝",
  "🧘‍♂️ Nimm das Leben nicht zu ernst – es nimmt dich auch nicht ernst 📶",
  "🙋‍♂️ Nicht perfekt ist auch okay 😂",
  "🧘‍♂️ Einfach mal machen. Wird schon irgendwie 📶",
];

function rotateSprueche() {
  const el = document.getElementById("spruch-des-moments");
  if (!el) return;

  el.style.textAlign = "center";

  let lastIndex = -1;

  function zeigeZufaelligenSpruch() {
    let newIndex;
    do {
      newIndex = Math.floor(Math.random() * sprueche.length);
    } while (newIndex === lastIndex);

    el.classList.remove("visible");
    setTimeout(() => {
      el.textContent = sprueche[newIndex];
      el.classList.add("visible");
      lastIndex = newIndex;
    }, 300);
  }
  zeigeZufaelligenSpruch();
  setInterval(zeigeZufaelligenSpruch, 6000);
}

window.addEventListener("DOMContentLoaded", () => {
  rotateSprueche();
});

